//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferenceData.Tests.SubdivisionServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SubdivisionServiceRef.ISubdivisionService")]
    public interface ISubdivisionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubdivisionService/GetSubdivisions", ReplyAction="http://tempuri.org/ISubdivisionService/GetSubdivisionsResponse")]
        ReferenceData.Model.Subdivision[] GetSubdivisions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubdivisionService/GetSubdivisions", ReplyAction="http://tempuri.org/ISubdivisionService/GetSubdivisionsResponse")]
        System.Threading.Tasks.Task<ReferenceData.Model.Subdivision[]> GetSubdivisionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubdivisionService/GetSubdivisionById", ReplyAction="http://tempuri.org/ISubdivisionService/GetSubdivisionByIdResponse")]
        ReferenceData.Model.Subdivision GetSubdivisionById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubdivisionService/GetSubdivisionById", ReplyAction="http://tempuri.org/ISubdivisionService/GetSubdivisionByIdResponse")]
        System.Threading.Tasks.Task<ReferenceData.Model.Subdivision> GetSubdivisionByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubdivisionService/GetItemsByCountryId", ReplyAction="http://tempuri.org/ISubdivisionService/GetItemsByCountryIdResponse")]
        ReferenceData.Model.Subdivision[] GetItemsByCountryId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubdivisionService/GetItemsByCountryId", ReplyAction="http://tempuri.org/ISubdivisionService/GetItemsByCountryIdResponse")]
        System.Threading.Tasks.Task<ReferenceData.Model.Subdivision[]> GetItemsByCountryIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubdivisionServiceChannel : ReferenceData.Tests.SubdivisionServiceRef.ISubdivisionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubdivisionServiceClient : System.ServiceModel.ClientBase<ReferenceData.Tests.SubdivisionServiceRef.ISubdivisionService>, ReferenceData.Tests.SubdivisionServiceRef.ISubdivisionService {
        
        public SubdivisionServiceClient() {
        }
        
        public SubdivisionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubdivisionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubdivisionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubdivisionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ReferenceData.Model.Subdivision[] GetSubdivisions() {
            return base.Channel.GetSubdivisions();
        }
        
        public System.Threading.Tasks.Task<ReferenceData.Model.Subdivision[]> GetSubdivisionsAsync() {
            return base.Channel.GetSubdivisionsAsync();
        }
        
        public ReferenceData.Model.Subdivision GetSubdivisionById(int id) {
            return base.Channel.GetSubdivisionById(id);
        }
        
        public System.Threading.Tasks.Task<ReferenceData.Model.Subdivision> GetSubdivisionByIdAsync(int id) {
            return base.Channel.GetSubdivisionByIdAsync(id);
        }
        
        public ReferenceData.Model.Subdivision[] GetItemsByCountryId(int id) {
            return base.Channel.GetItemsByCountryId(id);
        }
        
        public System.Threading.Tasks.Task<ReferenceData.Model.Subdivision[]> GetItemsByCountryIdAsync(int id) {
            return base.Channel.GetItemsByCountryIdAsync(id);
        }
    }
}
